### ISSUE TITLE
Reprovision `jenkins-nix-ci` as remote builder

### ISSUE THREAD

**Issue by srid** [nammayatri/ci#6]
## Tasks

- [ ] @vsaimanohar Connect the machine to ethernet
- [ ] @vsaimanohar Give the new IP address to Srid
- [ ] @srid Add configuration in this repo and deploy
- [ ] @srid Setup remote builder

**Comment by srid** [comment]
> * @vsaimanohar Give the new IP address to Srid

Sai says `192.168.10.238`

**Comment by srid** [comment]
@vsaimanohar Could you add this machine to the same tailscale network also?

**Comment by srid** [comment]
This would enable a 2nd i9 machine to do CI builds on, which is going to fasten the CI builds overall.

**Comment by vsaimanohar** [comment]
@srid that ip is internal ip address of 'basantis-mac-studio' , i have tried

```
~ ipconfig getifaddr en0
empty

ipconfig getifaddr en1
192.168.11.162
```
so lets use 192.168.11.162 Ethernet ipaddress instead here which is required right?
