### ISSUE TITLE
Add Mac Studio as builder

### ISSUE THREAD

**Issue by srid** [nammayatri/ci#7]
## Tasks

- Preparation
	- [x] @vsaimanohar Connect Mac Studio to ethernet
	- [x] @vsaimanohar Get access to an admin user
	- [x] @vsaimanohar Enable Remote Login (SSH), and test ssh'ing as this admin user
	- [x] @vsaimanohar Provide username, password and IP address to Srid
- Setup
    - [x] @srid Install Nix and add nix-configuration in this repo #10 
    - [x] @srid Setup mac studio as remote builder, and test in CI #11

**Comment by srid** [comment]
#10 added the nix-darwin configuration for the basanti-Mac-Studio.

**Comment by srid** [comment]
This is done. I'll improve things further, before merging the nammayatri PR.
